dataset = "eurosat_rgb"
net = "efficientnet-lite0"
batch_size = 32
p_cutoff = 0.95
lr = 0.01
uratio = 7
weight_decay = 7.5e-4
ulb_loss_ratio = 1.0
seed = 42
num_labels = 50
opt = "SGD"
save_dir = "./saved_models"
save_name_root = "test"
ema_m = 0.999
eval_batch_size = 1024
momentum = 0.9
T = 0.5
epoch = 100
amp = false
pretrained = false
hard_label = true
multiprocessing_distributed = false
num_eval_iter = 1000
scale=1


